name: Improve Code with Ollama

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  improve-code:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Uninstall Conflicting Packages and Install Docker
      - name: Install Docker
        run: |
          # Remove containerd to avoid conflicts
          sudo apt-get remove -y containerd

          # Install Docker dependencies
          sudo apt-get update
          sudo apt-get install -y \
            apt-transport-https \
            ca-certificates \
            curl \
            software-properties-common

          # Add Docker’s official GPG key
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

          # Add Docker’s APT repository
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

          # Install Docker
          sudo apt-get update
          sudo apt-get install -y docker-ce docker-ce-cli containerd.io

          # Verify Docker installation
          docker --version

      # Step 3: Pull the Ollama Docker Image
      - name: Pull Ollama Docker Image
        run: |
          docker pull ollama/ollama:latest

      # Step 4: Scan and Improve Code
      - name: Improve Code Using Ollama
        run: |
          # Find all relevant code files
          find . -type f \( -name "*.py" -o -name "*.js" -o -name "*.java" \) > code_files.txt

          # Loop through each file and improve its content using Ollama
          while IFS= read -r file; do
            echo "Processing $file"
            content=$(cat "$file")

            # Use Ollama CLI inside Docker to improve code
            improved_code=$(echo "$content" | docker run --rm -i ollama/ollama chat --model "your-ollama-model" --input "Improve this code")

            # Write the improved code back to the file
            echo "$improved_code" > "$file"
          done < code_files.txt

      # Step 5: Commit and Push Changes
      - name: Commit and Push Changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add .
          git commit -m "Improved code using Ollama"
          git push
